### ISSUE TITLE
Well that's nice

### ISSUE THREAD

**Issue by DeleteThisAcount** [quat1024/Cascade#2]
First of all this is a nice thing that your working on here.

NOW PLEASE DONT SWEAR! 

Ughh i wish I could report you but I guess your already deleted.

Any secondary acounts?

**Comment by quat1024** [comment]
fuck off

**Comment by quat1024** [comment]
https://cdn.discordapp.com/attachments/216257015863967766/348895899273134090/image.png

u rn

thank mr @eq
